data:
  id: BLCA
  params:
    data_dir: /work/mech-ai-scratch/tirtho/RecusrsiveQFormer/data/blca
    labels_filename: patient_labels.csv
    random_state: 42
    selected_genes_filename: null
    test_size: 0.2
    val_size: 0.1
    zscore_cnv: false
  type: brca
models:
  id: P-net_BLCA
  params:
    build_fn: !!python/name:model.builders.prostate_models.build_pnet2 ''
    feature_importance: null
    fitting_params:
      batch_size: 16
      class_weight: auto
      debug: false
      early_stop: false
      epoch: 200
      lr: 0.0001
      max_f1: true
      monitor: val_o2_f1
      n_outputs: 2
      prediction_output: average
      reduce_lr: false
      reduce_lr_after_nepochs:
        drop: 0.25
        epochs_drop: 50
      samples_per_epoch: 10
      save_gradient: false
      save_name: pnet
      select_best_model: false
      shuffle: true
      verbose: 2
    model_params:
      activation: tanh
      add_unk_genes: false
      attention: false
      data_params:
        id: BLCA
        params:
          data_dir: /work/mech-ai-scratch/tirtho/RecusrsiveQFormer/data/blca
          labels_filename: patient_labels.csv
          random_state: 42
          selected_genes_filename: null
          test_size: 0.2
          val_size: 0.1
          zscore_cnv: false
        type: brca
      dropout:
      - 0.2
      - 0.1
      - 0.1
      dropout_testing: false
      kernel_initializer: lecun_uniform
      loss_weights:
      - 2
      - 7
      n_hidden_layers: 1
      optimizer: Adam
      shuffle_genes: false
      use_bias: true
      w_reg:
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      w_reg_outcomes:
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
  type: nn
pipeline:
  params:
    n_splits: 5
    save_train: true
  type: crossvalidation
pre:
  type: null
scores: '{"accuracy":{"0":0.5555555556,"1":0.5802469136,"2":0.5925925926,"3":0.5432098765,"4":0.6},"precision":{"0":0.6507936508,"1":0.6567164179,"2":0.6666666667,"3":0.649122807,"4":0.6964285714},"auc":{"0":0.4601398601,"1":0.4545454545,"2":0.4412587413,"3":0.5720164609,"4":0.5270655271},"f1":{"0":0.6949152542,"1":0.7213114754,"2":0.7272727273,"3":0.6666666667,"4":0.7090909091},"f1_macro":{"0":0.438366718,"1":0.4356557377,"2":0.4611973392,"3":0.4705882353,"4":0.5345454545},"aupr":{"0":0.668015351,"1":0.6959028711,"2":0.6758113179,"3":0.7837064245,"4":0.6954443315},"recall":{"0":0.7454545455,"1":0.8,"2":0.8,"3":0.6851851852,"4":0.7222222222}}'
scores_mean: '{"accuracy":0.5743209877,"precision":0.6639456228,"auc":0.4910052088,"f1":0.7038514065,"f1_macro":0.468070697,"aupr":0.7037760592,"recall":0.7505723906}'
scores_std: '{"accuracy":0.0242302626,"precision":0.0194132537,"auc":0.056169084,"f1":0.0242044642,"f1_macro":0.0400172787,"aupr":0.0463171757,"recall":0.049978966}'
