data:
  id: STAD
  params:
    data_dir: /work/mech-ai-scratch/tirtho/RecusrsiveQFormer/data/stad
    labels_filename: patient_labels.csv
    random_state: 42
    selected_genes_filename: null
    test_size: 0.2
    val_size: 0.1
    zscore_cnv: false
  type: brca
models:
  id: P-net_STAD
  params:
    build_fn: !!python/name:model.builders.prostate_models.build_pnet2 ''
    feature_importance: null
    fitting_params:
      batch_size: 16
      class_weight: auto
      debug: false
      early_stop: false
      epoch: 200
      lr: 0.0001
      max_f1: true
      monitor: val_o2_f1
      n_outputs: 2
      prediction_output: average
      reduce_lr: false
      reduce_lr_after_nepochs:
        drop: 0.25
        epochs_drop: 50
      samples_per_epoch: 10
      save_gradient: false
      save_name: pnet
      select_best_model: false
      shuffle: true
      verbose: 2
    model_params:
      activation: tanh
      add_unk_genes: false
      attention: false
      data_params:
        id: STAD
        params:
          data_dir: /work/mech-ai-scratch/tirtho/RecusrsiveQFormer/data/stad
          labels_filename: patient_labels.csv
          random_state: 42
          selected_genes_filename: null
          test_size: 0.2
          val_size: 0.1
          zscore_cnv: false
        type: brca
      dropout:
      - 0.2
      - 0.1
      - 0.1
      dropout_testing: false
      kernel_initializer: lecun_uniform
      loss_weights:
      - 2
      - 7
      n_hidden_layers: 1
      optimizer: Adam
      shuffle_genes: false
      use_bias: true
      w_reg:
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      w_reg_outcomes:
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
  type: nn
pipeline:
  params:
    n_splits: 5
    save_train: true
  type: crossvalidation
pre:
  type: null
scores: '{"accuracy":{"0":0.4939759036,"1":0.4819277108,"2":0.5301204819,"3":0.5421686747,"4":0.4756097561},"precision":{"0":0.5294117647,"1":0.5294117647,"2":0.5813953488,"3":0.5666666667,"4":0.5217391304},"auc":{"0":0.516374269,"1":0.4306698002,"2":0.5299647474,"3":0.4412455934,"4":0.4636636637},"f1":{"0":0.5625,"1":0.5567010309,"2":0.5617977528,"3":0.641509434,"4":0.5274725275},"f1_macro":{"0":0.48125,"1":0.4667563126,"2":0.5276521232,"3":0.5040880503,"4":0.4692157158},"aupr":{"0":0.534202478,"1":0.5236973559,"2":0.6060781766,"3":0.5077864192,"4":0.5270861919},"recall":{"0":0.6,"1":0.5869565217,"2":0.5434782609,"3":0.7391304348,"4":0.5333333333}}'
scores_mean: '{"accuracy":0.5047605054,"precision":0.5457249351,"auc":0.4763836147,"f1":0.569996149,"f1_macro":0.4897924404,"aupr":0.5397701243,"recall":0.6005797101}'
scores_std: '{"accuracy":0.0297065223,"precision":0.0265447378,"auc":0.0445993855,"f1":0.0424928654,"f1_macro":0.0258106476,"aupr":0.0383077339,"recall":0.0824088608}'
