data:
  id: PROSTATE
  params:
    data_dir: /work/mech-ai-scratch/tirtho/RecusrsiveQFormer/data/prostate
    labels_filename: patient_labels.csv
    random_state: 42
    selected_genes_filename: null
    test_size: 0.2
    val_size: 0.1
    zscore_cnv: false
  type: brca
models:
  id: P-net_PROSTATE
  params:
    build_fn: !!python/name:model.builders.prostate_models.build_pnet2 ''
    feature_importance: null
    fitting_params:
      batch_size: 16
      class_weight: auto
      debug: false
      early_stop: false
      epoch: 200
      lr: 0.0001
      max_f1: true
      monitor: val_o2_f1
      n_outputs: 2
      prediction_output: average
      reduce_lr: false
      reduce_lr_after_nepochs:
        drop: 0.25
        epochs_drop: 50
      samples_per_epoch: 10
      save_gradient: false
      save_name: pnet
      select_best_model: false
      shuffle: true
      verbose: 2
    model_params:
      activation: tanh
      add_unk_genes: false
      attention: false
      data_params:
        id: PROSTATE
        params:
          data_dir: /work/mech-ai-scratch/tirtho/RecusrsiveQFormer/data/prostate
          labels_filename: patient_labels.csv
          random_state: 42
          selected_genes_filename: null
          test_size: 0.2
          val_size: 0.1
          zscore_cnv: false
        type: brca
      dropout:
      - 0.2
      - 0.1
      - 0.1
      dropout_testing: false
      kernel_initializer: lecun_uniform
      loss_weights:
      - 2
      - 7
      n_hidden_layers: 1
      optimizer: Adam
      shuffle_genes: false
      use_bias: true
      w_reg:
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      w_reg_outcomes:
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
  type: nn
pipeline:
  params:
    n_splits: 5
    save_train: true
  type: crossvalidation
pre:
  type: null
scores: '{"accuracy":{"0":0.8965517241,"1":0.8217821782,"2":0.8663366337,"3":0.8168316832,"4":0.8514851485},"precision":{"0":0.8285714286,"1":0.6781609195,"2":0.8703703704,"3":0.6835443038,"4":0.7903225806},"auc":{"0":0.9336040386,"1":0.9094527363,"2":0.9258153676,"3":0.9112076649,"4":0.8936051693},"f1":{"0":0.8467153285,"1":0.7662337662,"2":0.7768595041,"3":0.7448275862,"4":0.765625},"f1_macro":{"0":0.884324207,"1":0.8111168831,"2":0.8407265719,"3":0.8009852217,"4":0.8284646739},"aupr":{"0":0.8855880931,"1":0.8260504847,"2":0.8877010644,"3":0.8224776879,"4":0.79303467},"recall":{"0":0.8656716418,"1":0.8805970149,"2":0.7014925373,"3":0.8181818182,"4":0.7424242424}}'
scores_mean: '{"accuracy":0.8505974735,"precision":0.7701939206,"auc":0.9147369954,"f1":0.780052237,"f1_macro":0.8331235115,"aupr":0.8429704,"recall":0.8016734509}'
scores_std: '{"accuracy":0.0329042251,"precision":0.0863519642,"auc":0.0155372881,"f1":0.0390321426,"f1_macro":0.0324737736,"aupr":0.0418835052,"recall":0.07769155}'
