#!/usr/bin/env python
"""Emit paper/pm_depth_tables.tex: complete per-pathway recursion-depth tables for the
PM cohort (K=4 expert- and token-choice), promised by the main-text Interpretability
section. Data: results/cv5/pm_routing/pm_routing.json. Fully reproducible."""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "results/cv5/pm_routing/pm_routing.json")
OUT = os.path.join(ROOT, "paper/pm_depth_tables.tex")
K, TOPN = 4, 25

d = json.load(open(SRC))
pw = d["pathways"]
R = {(e["routing"], e["K"]): e for e in d["results"]}


def esc(s):
    return str(s).replace("_", r"\_")


def ranked(routing):
    md = R[(routing, K)]["mean_depth"]
    return sorted(zip(pw, md), key=lambda x: x[1], reverse=True)


def two_col(routing):
    pairs = ranked(routing)
    kept = pairs[:TOPN]
    dropped = list(reversed(pairs[-TOPN:]))  # earliest-exit first
    def col(rows):
        out = [r"\begin{tabular}{@{}r l r@{}}\toprule", r"\# & Pathway & $d_m$ \\\midrule"]
        for i, (p, dep) in enumerate(rows, 1):
            out.append(f"{i} & \\texttt{{{esc(p)}}} & {dep:.2f} \\\\")
        out.append(r"\bottomrule\end{tabular}")
        return "\n".join(out)
    return col(kept), col(dropped)


# overlap between the two KEPT sets (for the honest note)
ek = {p for p, _ in ranked("expert")[:TOPN]}
tk = {p for p, _ in ranked("token")[:TOPN]}
overlap = len(ek & tk)

lines = [
    r"% AUTO-GENERATED by scripts/build_pm_depth_tables.py --- do not edit by hand.",
    r"\section{Per-Pathway Recursion-Depth Tables}",
    r"\label{app:pmdepth}",
    rf"Complete keep/drop rankings for the PM cohort (pan-cancer, mutation$+$copy-number; "
    rf"${d['n_pathways']}$ Reactome pathway tokens, {d['n_samples']} samples) under canonical "
    rf"bioMoR at $K{{=}}{K}$, referenced from the main-text Interpretability section. Mean "
    rf"recursion depth $d_m\in[0,{K}]$ is averaged over the same 5 held-out folds as the main "
    rf"table. Higher $d_m$ = the router keeps allocating compute (\emph{{kept}}); the minimum = "
    rf"early exit (\emph{{dropped}}). The two routing rules keep \emph{{different}} pathways: "
    rf"their top-{TOPN} kept sets share {overlap} pathways and their per-pathway depths are "
    rf"weakly anti-correlated (Spearman $-0.28$), so each ranking is read within its routing mode.",
]

for routing, macro in [("expert", R[("expert", K)]), ("token", R[("token", K)])]:
    kept_t, dropped_t = two_col(routing)
    lines += [
        rf"\subsection{{{routing.capitalize()}-choice ($K{{=}}{K}$, Macro-F1 "
        rf"{macro['f1_mean']:.1f}$\pm${macro['f1_sd']:.1f})}}",
        r"\begin{center}\footnotesize",
        r"\begin{minipage}[t]{0.48\linewidth}\centering",
        r"\textbf{Kept --- 25 deepest-routed}\\[2pt]",
        kept_t,
        r"\end{minipage}\hfill",
        r"\begin{minipage}[t]{0.48\linewidth}\centering",
        r"\textbf{Dropped --- 25 earliest-exit}\\[2pt]",
        dropped_t,
        r"\end{minipage}",
        r"\end{center}",
    ]

with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", OUT, "| kept-set overlap =", overlap)
